apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: fullstaq-ruby
data:
  default.conf: |
    server {
      listen 8001;
      server_name apt.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://dl.bintray.com/fullstaq/fullstaq-ruby-apt/$1 redirect;
      }
    }

    server {
      listen 8002;
      server_name yum.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://dl.bintray.com/fullstaq/fullstaq-ruby-yum/$1 redirect;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: fullstaq-ruby
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - gateway
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
            - containerPort: 8002
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: gateway
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: fullstaq-ruby
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - name: apt
      protocol: TCP
      port: 8001
      nodePort: 30701
    - name: yum
      protocol: TCP
      port: 8002
      nodePort: 30702
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: fullstaq-ruby
spec:
  rules:
    - host: apt.fullstaqruby.org
      http:
        paths:
          - backend:
              serviceName: gateway
              servicePort: 8001
    - host: yum.fullstaqruby.org
      http:
        paths:
          - backend:
              serviceName: gateway
              servicePort: 8002
