apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  default.conf: |
    server {
      listen 80;
      server_name apt.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          # Satisfy Google Cloud Balancer health check
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/1/$1 redirect;
      }
    }

    server {
      listen 80;
      server_name yum.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          # Satisfy Google Cloud Balancer health check
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://storage.googleapis.com/fullstaq-ruby-server-edition-yum-repo/versions/1/$1 redirect;
      }
    }
