apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: init
          image: nginx:1.19-alpine
          command:
            - /bin/sh
            - '-c'
            - |
              set -e

              APT_LATEST_VERSION=$(curl -fsSL https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/latest_version.txt)
              YUM_LATEST_VERSION=$(curl -fsSL https://storage.googleapis.com/fullstaq-ruby-server-edition-yum-repo/versions/latest_version.txt)

              echo "+ APT latest version: $APT_LATEST_VERSION"
              echo "+ YUM latest version: $YUM_LATEST_VERSION"

              for F in /mnt/config/*; do
                NAME=$(basename "$F")
                echo "+ Processing $NAME"
                sed "s|{APT_LATEST_VERSION}|$APT_LATEST_VERSION|g; s|{YUM_LATEST_VERSION}|$YUM_LATEST_VERSION|g" \
                  "$F" > "/mnt/processed-config/$NAME"
              done
          resources:
            requests:
              cpu: 250m
              memory: 32Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 250m
              memory: 32Mi
              ephemeral-storage: 32Mi
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: processed-config
              mountPath: /mnt/processed-config
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 2
            timeoutSeconds: 10
            httpGet:
              port: 80
              path: /
              httpHeaders:
                - name: User-Agent
                  value: Kubernetes Readiness Probe
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 512Mi
          volumeMounts:
            - name: processed-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: gateway
        - name: processed-config
          emptyDir: {}
