kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - name: apt
      protocol: TCP
      port: 8001
      nodePort: 30701
    - name: yum
      protocol: TCP
      port: 8002
      nodePort: 30702
