apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  default.conf: |
    server {
      listen 8001;
      server_name apt.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://dl.bintray.com/fullstaq/fullstaq-ruby-apt/$1 redirect;
      }
    }

    server {
      listen 8002;
      server_name yum.fullstaqruby.org;

      location / {
        if ($http_user_agent ~* "GoogleHC") {
          return 200 'OK';
        }
        rewrite ^/(.*)$ https://dl.bintray.com/fullstaq/fullstaq-ruby-yum/$1 redirect;
      }
    }
