apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: gateway
spec:
  domains:
    - apt.fullstaqruby.org
    - yum.fullstaqruby.org
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    networking.gke.io/managed-certificates: gateway
    kubernetes.io/ingress.global-static-ip-name: fullstaq-ruby-packages-gateway
    kubernetes.io/ingress.class: gce
spec:
  defaultBackend:
    service:
      name: gateway
      port:
        number: 80
